tweet_producers:
  - id: trump
    keywords: donald trump
env:
  TWEET_OAUTH_CONSUMER_KEY: ""
  TWEET_OAUTH_CONSUMER_SECRET: ""
  TWEET_OAUTH_TOKEN_KEY: ""
  TWEET_OAUTH_TOKEN_SECRET: ""
  TWEET_PRODUCER_KAFKA_TOPIC: "dem-tweets"
tweet_producer_version: "latest"
tweet_consumer_version: "latest"
